version: '3.0'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.33
    command: --default-authentication-plugin=mysql_native_password --collation-server=utf8_general_ci --character-set-server=utf8 --sql_mode="" --skip-log-bin
    restart: always
    volumes:
      - ./Db.sql:/docker-entrypoint-initdb.d/newgen.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      MYSQL_DATABASE: 'newgen'
    ports:
      - '3308:3306'
    networks:
      - newgen
#  chrome:
#    image: zenika/alpine-chrome:latest
#    container_name: chrome
#    command: [ chromium-browser, "--headless", "--disable-gpu", "--no-sandbox", "--remote-debugging-address=0.0.0.0", "--remote-debugging-port=9222" ]
#    ports:
#      - "9222:9222"
#    networks:
#      - newgen
  php:
    platform: linux/x86_64
    build:
      context: ./php8.3
    container_name: php
    stdin_open: true
    depends_on:
      - mysql
#      - chrome
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/newgenParser
    networks:
      - newgen
networks:
  newgen:
    driver: bridge